-- CreateTable
CREATE TABLE "ExamSubject" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "title" TEXT NOT NULL DEFAULT '',
    "description" TEXT NOT NULL DEFAULT '',
    "minScore" INTEGER NOT NULL DEFAULT 20,
    "type" TEXT NOT NULL DEFAULT 'main'
);
