import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { ColorSchemeScript } from "@mantine/core";

export const metadata: Metadata = {
  title: "Калькулятор баллов ЕГЭ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
